[[main]]
  name = "Trang chủ"
  url = "/"
  weight = 1

[[main]]
  name = "Tình nguyện viên"
  url = "/volunteers/"
  weight = 2

[[main]]
  name = "Học bổng"
  url = "/sponsorships/"
  weight = 3

[[main]]
  name = "Tài trợ dự án"
  url = "/projects/"
  weight = 4

[[main]]
  name = "Dự án tiêu biểu"
  url = "/success-stories/"
  weight = 5

[[main]]
  name = "Minh bạch & Pháp lý"
  url = "/trust-and-compliance/"
  weight = 6

[[main]]
  name = "Hỏi đáp"
  url = "/faq/"
  weight = 7

[[main]]
  name = "Liên hệ"
  url = "/contact/"
  weight = 8